import json
from pathlib import Path
import pandas as pd

# === Params you can edit directly ===
FONT_PX           = 11
TOP_SPONSORS      = 0
TOP_INTERVENTIONS = 0

# Inputs/outputs (linked to the previous script’s artifacts)
in_csv   = Path("public") / "upcoming_trials_next3m_sorted.csv"
out_html = Path("public") / "upcoming_trials_charts.html"

# Load the CSV created by the table script
df = pd.read_csv(in_csv)

# Ensure expected columns (rename defensively if needed)
expected_cols = {
    "event_date","event_type","event_date_type","nct_id","title","phase_std","status",
    "enrollment","enrollment_type","lead_sponsor","intervention_types","interventions",
    "conditions","last_update_posted_date"
}
missing = expected_cols - set(df.columns)
if missing:
    raise SystemExit(f"Missing expected columns in CSV: {sorted(missing)}")

# Serialize data to embed in the HTML (avoid NaNs for JS)
records = json.loads(df.to_json(orient="records"))

PHASE_ORDER  = ["Early Phase 1","Phase 1","Phase 1/2","Phase 2","Phase 2/3","Phase 3","Phase 4","Not Applicable","Unknown"]
STATUS_ORDER = ["RECRUITING","ACTIVE_NOT_RECRUITING","ENROLLING_BY_INVITATION","NOT_YET_RECRUITING",
                "SUSPENDED","TERMINATED","COMPLETED","WITHDRAWN","UNKNOWN"]

html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Upcoming Trials (next 3 months) — Charts</title>
<style>
  html, body {{
    background:#fff; margin:16px; font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
    font-size: {FONT_PX}px;
  }}
  .toolbar {{
    display:flex; flex-wrap:wrap; gap:12px; align-items:center; margin: 4px 0 12px;
  }}
  .toolbar label {{ display:flex; gap:6px; align-items:center; }}
  select, input[type="number"], button {{
    font-size:{FONT_PX}px; padding:4px 8px; border-radius:8px; border:1px solid #ddd; background:#fff;
  }}
  .grid {{
    display:grid; gap:16px; margin-top:8px; grid-template-columns: repeat(12, 1fr);
  }}
  .card {{
    grid-column: span 12; background:#fff; border:1px solid #eee; border-radius:12px; padding:12px;
  }}
  .card h3 {{ margin:0 0 8px; font-size:{FONT_PX + 2}px; }}
  @media (min-width: 900px) {{
    #card_phase_sponsor {{ grid-column: span 12; }}
    #card_phase_total, #card_status_total {{ grid-column: span 6; }}
    #card_intervention_total {{ grid-column: span 12; }}
  }}
  .muted {{ opacity:0.75; }}
</style>
</head>
<body>

<h2 style="margin:0 0 2px;">Upcoming Trials (next 3 months) — Charts</h2>
<div class="muted" style="margin-bottom:10px;">This page reads the dataset generated by the table page and can also honor a sponsor filter from URL or localStorage.</div>

<div class="toolbar">
  <label>Filter sponsors:
    <select id="sponsorFilter" multiple size="6" style="min-width:240px;"></select>
  </label>
  <label>Top sponsors:
    <input id="topSponsors" type="number" min="3" max="50" value="{TOP_SPONSORS}"/>
  </label>
  <label>Top intervention types:
    <input id="topInterventions" type="number" min="5" max="100" value="{TOP_INTERVENTIONS}"/>
  </label>
  <button id="applyBtn">Apply</button>
  <button id="clearBtn">Clear filters</button>
</div>

<div class="grid">
  <div id="card_phase_sponsor" class="card">
    <h3>Trials per Phase per Lead Sponsor (Top-N by total in view)</h3>
    <div id="chart_phase_sponsor"></div>
  </div>
  <div id="card_phase_total" class="card">
    <h3>Total Trials per Phase</h3>
    <div id="chart_phase_total"></div>
  </div>
  <div id="card_status_total" class="card">
    <h3>Total Trials per Status</h3>
    <div id="chart_status_total"></div>
  </div>
  <div id="card_intervention_total" class="card">
    <h3>Intervention Type Counts</h3>
    <div id="chart_intervention_total"></div>
  </div>
</div>

<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<script>
  // === Embedded data (from CSV) ===
  const DATA = {json.dumps(records, ensure_ascii=False)};
  const PHASE_ORDER = {json.dumps(PHASE_ORDER)};
  const STATUS_ORDER = {json.dumps(STATUS_ORDER)};

  // === Helpers ===
  const clean = (v) => (v == null ? "" : String(v).trim());
  const uniq = (arr) => Array.from(new Set(arr));

  function getUrlSponsors() {{
    const url = new URL(window.location.href);
    const raw = url.searchParams.get('sponsor');
    if (!raw) return [];
    return raw.split(',').map(s => s.trim()).filter(Boolean);
  }}

  function getLocalStorageSponsors() {{
    try {{
      // prefer a simple key with a value like "Pfizer,Novartis"
      const raw = localStorage.getItem('upcoming_trials_sponsor') || "";
      const list = raw.split(',').map(s => s.trim()).filter(Boolean);
      if (list.length) return list;

      // or a JSON blob with .sponsor or .sponsors fields
      const blob = JSON.parse(localStorage.getItem('upcoming_trials_filter') || "null");
      if (blob) {{
        if (Array.isArray(blob.sponsors)) return blob.sponsors.map(clean).filter(Boolean);
        if (blob.sponsor) return [clean(blob.sponsor)].filter(Boolean);
      }}
    }} catch (e) {{}}
    return [];
  }}

  function initialSponsorSelection(allSponsors) {{
    const fromUrl  = getUrlSponsors();
    const fromLS   = getLocalStorageSponsors();
    const seed = (fromUrl.length ? fromUrl : fromLS);
    return seed.filter(s => allSponsors.includes(s));
  }}

  function filterDataBySponsors(rows, selectedSponsors) {{
    if (!selectedSponsors || !selectedSponsors.length) return rows;
    const set = new Set(selectedSponsors.map(clean));
    return rows.filter(r => set.has(clean(r.lead_sponsor) || "Unknown"));
  }}

  function countBy(arr, key) {{
    const m = new Map();
    for (const r of arr) {{
      const k = clean(r[key] || "");
      m.set(k, (m.get(k) || 0) + 1);
    }}
    return m;
  }}

  function countSponsorPhase(arr) {{
    const m = new Map(); // sponsor -> Map(phase -> count)
    for (const r of arr) {{
      const s = clean(r.lead_sponsor || "Unknown") || "Unknown";
      const p = clean(r.phase_std || "Unknown") || "Unknown";
      if (!m.has(s)) m.set(s, new Map());
      const inner = m.get(s);
      inner.set(p, (inner.get(p) || 0) + 1);
    }}
    return m;
  }}

  function countInterventionTypes(arr) {{
    const m = new Map();
    for (const r of arr) {{
      const raw = clean(r.intervention_types || "");
      if (!raw) continue;
      raw.split(',').forEach(part => {{
        const t = part.trim();
        if (!t) return;
        m.set(t, (m.get(t) || 0) + 1);
      }});
    }}
    return m;
  }}

  // === UI wiring ===
  const sponsorSelect = document.getElementById('sponsorFilter');
  const topSponsorsInput = document.getElementById('topSponsors');
  const topIntervInput   = document.getElementById('topInterventions');

  const allSponsors = uniq(DATA.map(r => clean(r.lead_sponsor || "Unknown") || "Unknown")).sort((a,b)=> a.localeCompare(b));
  // Populate multi-select
  for (const s of allSponsors) {{
    const opt = document.createElement('option');
    opt.value = s;
    opt.textContent = s;
    sponsorSelect.appendChild(opt);
  }}

  // Preselect from URL/localStorage if present
  const pre = initialSponsorSelection(allSponsors);
  if (pre.length) {{
    [...sponsorSelect.options].forEach(o => o.selected = pre.includes(o.value));
  }}

  function getSelectedSponsors() {{
    return [...sponsorSelect.selectedOptions].map(o => o.value);
  }}

  // === Chart rendering ===
  function updateCharts() {{
    const selectedSponsors = getSelectedSponsors();
    const view = filterDataBySponsors(DATA, selectedSponsors);

    // Sponsor-Phase (Top-N)
    const topN = Math.max(1, Math.min(50, Number(topSponsorsInput.value) || {TOP_SPONSORS}));
    const spMap = countSponsorPhase(view);
    const sponsorTotals = Array.from(spMap.entries()).map(([s, mp]) => [s, Array.from(mp.values()).reduce((a,b)=>a+b,0)]);
    sponsorTotals.sort((a,b)=> b[1]-a[1]);
    const topSponsors = sponsorTotals.slice(0, topN).map(d => d[0]);

    const tracesSP = PHASE_ORDER.map(phase => {{
      const y = topSponsors.map(s => {{
        const mp = spMap.get(s);
        return mp ? (mp.get(phase) || 0) : 0;
      }});
      return {{ type:'bar', name: phase, x: topSponsors, y }};
    }});
    Plotly.react('chart_phase_sponsor', tracesSP, {{
      barmode:'stack',
      xaxis: {{ automargin: true }},
      yaxis: {{ title: 'Trials', rangemode: 'tozero' }},
      margin: {{ t: 10, r: 10, b: 60, l: 50 }},
      showlegend: true
    }});

    // Total per Phase
    const byPhase = countBy(view, 'phase_std');
    const phaseCats = PHASE_ORDER.filter(p => byPhase.has(p))
      .concat(Array.from(byPhase.keys()).filter(p => !PHASE_ORDER.includes(p)));
    const phaseVals = phaseCats.map(p => byPhase.get(p) || 0);
    Plotly.react('chart_phase_total', [{{type:'bar', x: phaseCats, y: phaseVals}}], {{
      xaxis: {{ tickangle: -30 }},
      yaxis: {{ title: 'Trials', rangemode: 'tozero' }},
      margin: {{ t: 10, r: 10, b: 80, l: 50 }}
    }});

    // Total per Status
    const byStatus = countBy(view, 'status');
    const statusCats = STATUS_ORDER.filter(s => byStatus.has(s))
      .concat(Array.from(byStatus.keys()).filter(s => !STATUS_ORDER.includes(s)));
    const statusVals = statusCats.map(s => byStatus.get(s) || 0);
    Plotly.react('chart_status_total', [{{type:'bar', x: statusCats, y: statusVals}}], {{
      xaxis: {{ tickangle: -30 }},
      yaxis: {{ title: 'Trials', rangemode: 'tozero' }},
      margin: {{ t: 10, r: 10, b: 80, l: 50 }}
    }});

    // Intervention types (Top-N)
    const topI = Math.max(1, Math.min(100, Number(topIntervInput.value) || {TOP_INTERVENTIONS}));
    const byInterv = countInterventionTypes(view);
    const sortedInterv = Array.from(byInterv.entries()).sort((a,b)=> b[1]-a[1]).slice(0, topI);
    Plotly.react('chart_intervention_total', [{{type:'bar', x: sortedInterv.map(d=>d[0]), y: sortedInterv.map(d=>d[1])}}], {{
      xaxis: {{ tickangle: -30 }},
      yaxis: {{ title: 'Trials', rangemode: 'tozero' }},
      margin: {{ t: 10, r: 10, b: 100, l: 50 }}
    }});
  }}

  // Buttons
  document.getElementById('applyBtn').addEventListener('click', updateCharts);
  document.getElementById('clearBtn').addEventListener('click', () => {{
    [...sponsorSelect.options].forEach(o => o.selected = false);
    updateCharts();
  }});

  // Initial render
  updateCharts();

  // Optional: auto-apply if localStorage changes in another tab
  window.addEventListener('storage', (e) => {{
    if (e.key === 'upcoming_trials_sponsor' || e.key === 'upcoming_trials_filter') {{
      // re-seed selection from localStorage
      const again = initialSponsorSelection(allSponsors);
      [...sponsorSelect.options].forEach(o => o.selected = again.includes(o.value));
      updateCharts();
    }}
  }});
</script>
</body>
</html>
"""

out_html.write_text(html, encoding="utf-8")
print("Wrote:", out_html)
